create table veiculos(
     id int AUTO_INCREMENT NOT NULL, 
     nome varchar(70) NOT NULL,
     categoria  varchar(70) NOT NULL.
     marca varchar(70) NOT NULL

);

insert into veiculos(nome, categoria, marca ) values(
    Tiggo 8,
    Automatico,
    caoa),
    ( Tiggo 7,
    Automatico, 
    caoa),
    (Arizzo 6,
    Automatico,
    caoa),
    (Cruze,
    Automatico,
    Chevrolet),
    (Nissan Rogue,
    Automatico,
    Nissan),
    (Onix, 
    Compacto, 
    Chevrolet),
    (Prisma, 
    Compacto, 
    Chevrolet),
    (Spark, 
    Compacto, 
    Chevrolet),
    (Ford Ka,
    Compacto,
    Ford),
    (Focus,
    Compacto,
    Ford),
    (Onix Joy, 
    Economico, 
    Chevrolet),
    (Siena, 
    Economico, 
    Fiat),
    (Malibu, 
    Executivo, 
    Chevrolet),
    (Cronos, 
    Executivo, 
    Fiat),
    (Fusion,
    Executivo,
    Ford),
    (Argo, 
    Hatch, 
    Fiat),
    (Mobi, 
    Hatch, 
    Fiat),
    (Cruze Hatch, 
    Hatch, 
    Chevrolet),
    (Kwid, 
    Hatch, 
    Renault),
    (Gol, 
    Hatch, 
    Volkswagen),
    (Picanto, 
    Hatch, 
    Kia),
    (Hb20, 
    Hatch, 
    Hyundai),
    (Spin, 
    Minivan, 
    Chevrolet),
    (Doblô, 
    Minivan, 
    Fiat),
    (Tucson, 
    Minivan,
    Hyundai),
    (SpaceFox, 
    Minivan,
    Volkswagen),
    (Duster, 
    Minivan,
    Renault),
    (Toro, 
    pick-up, 
    Fiat),
    (Cruze Sedan, 
    Sedan, 
    Chevrolet),
    (Onix Sedan, 
    Sedan, 
    Chevrolet),
    (Grand Siena, 
    Sedan, 
    Fiat),
    (Ford Ka Sedan, 
    Sedan, 
    Ford),
    (Hb20S, 
    Sedan, 
    Hyundai),
    (Cerato, 
    Sedan, 
    Kia),
    (Logan, 
    Sedan, 
    Chevrolet),
    (Tracker, 
    Suv, 
    Chevrolet),
    (Trailblazer, 
    Suv, 
    Chevrolet),
    (Toro, 
    Suv, 
    Fiat),
    (Sportage, 
    Suv, 
    Kia),
    (Strada, 
    Suv, 
    Fiat),
    (EcoSport, 
    Suv, 
    Ford);